import express from "express";
import { login, logout, signup } from "../controllers/authController.js";
import { protectRoute } from "../middleware/authMiddleware.js";
import { updateUserDetails, checkAuth} from "../controllers/authController.js";
const router = express.Router();
router.post("/signup", signup);
router.post("/login", login);
router.post("/logout", logout);
router.put("/update-profile", protectRoute, updateUserDetails);
router.get("/check", protectRoute, checkAuth);
export default router;